import type { Metadata } from "next";
import "@/globals.css";
import { QueryClientProvider } from "@/providers/QueryClientProvider";
import { PageLoadProvider } from "@/providers/pageLoadProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryClientProvider>
          <PageLoadProvider>{children}</PageLoadProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
